############################################
# GLOBAL VARS

variables:
  XCODE_PROJECT: MoyaModelMapper.xcodeproj
  BASE_SCHEME: MoyaModelMapper
  GIT_STRATEGY: fetch

############################################
# STAGES

stages:
  - moya
  - reactive
  - demo
  - podlint

############################################
# JOBS

before_script:
  - brew update
  # Cocoapod
  - brew outdated cocoapods || brew upgrade cocoapods
  # SwiftLint
  - brew outdated swiftlint || brew upgrade swiftlint
  # Carthage tools
  - brew outdated carthage || brew upgrade carthage
  # - curl -L -O https://github.com/YPlan/CartfileDiff/releases/download/0.1/CartfileDiff.pkg
  # - sudo installer -pkg CartfileDiff.pkg -target /
  # xcpretty
  - if ! gem list xcpretty -i > /dev/null 2>&1; then 
      gem install xcpretty;
    fi

  # bootstrap the dependencies for the project
  # you can remove if you don't have dependencies
  - PLATFORM=$PLATFORM ./scripts/bootstrap-if-needed

after_script:
  - osascript -e 'tell app "Simulator" to quit'

############################################
# TEMPLATES

.cache: &cache_paths
  paths:
  - Carthage

.script_template: &script
  script:
    - set -o pipefail

    - SCHEME="$PREFIX$BASE_SCHEME"
    
    # Build Framework in Debug and Run Tests if specified
    - xcodebuild clean -project "$XCODE_PROJECT" -scheme "$SCHEME" | xcpretty
    - xcodebuild -project "$XCODE_PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES $ACTION | xcpretty;

    # Build Framework in Release and Run Tests if specified
    - xcodebuild clean -project "$XCODE_PROJECT" -scheme "$SCHEME" | xcpretty
    - xcodebuild -project "$XCODE_PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES $ACTION | xcpretty;

.iOS_vars: &iOS_vars
  PLATFORM: iOS
  SDK: iphonesimulator10.3
  ACTION: test
  DESTINATION: "platform=iOS Simulator,OS=10.3,name=iPhone 7"

.macOS_vars: &macOS_vars
  PLATFORM: macOS
  SDK: macosx10.12
  ACTION: test
  DESTINATION: "platform=OS X,arch=x86_64"

.tvOS_vars: &tvOS_vars
  PLATFORM: tvOS
  SDK: appletvsimulator10.2
  ACTION: test
  DESTINATION: "OS=10.2,name=Apple TV 1080p"

.watchOS_vars: &watchOS_vars
  PLATFORM: watchOS
  SDK: watchsimulator3.2
  ACTION: build
  DESTINATION: "platform=watchOS Simulator,OS=3.2,name=Apple Watch Series 2 - 42mm"

############################################
# JOBS - STAGE: TEST

# iPhone 7
iPhone 7 - OS 10.3:
  stage: moya
  cache:
    <<: *cache_paths
    key: iOS
  tags:
    - xcode
    - iOS
  <<: *script
  variables:
    <<: *iOS_vars

Rx iPhone 7 - OS 10.3:
  stage: reactive
  cache:
    <<: *cache_paths
    key: iOS
  tags:
    - xcode
    - iOS
  <<: *script
  variables:
    <<: *iOS_vars
    PREFIX: Rx

Reactive iPhone 7 - OS 10.3:
  stage: reactive
  cache:
    <<: *cache_paths
    key: iOS
  tags:
    - xcode
    - iOS
  <<: *script
  variables:
    <<: *iOS_vars
    PREFIX: Reactive

# macOS
macOS - OS 10.12:
  stage: moya
  cache:
    <<: *cache_paths
    key: macOS
  tags:
    - xcode
    - macOS
  <<: *script
  variables:
    <<: *macOS_vars

Rx macOS - OS 10.12:
  stage: reactive
  cache:
    <<: *cache_paths
    key: macOS
  tags:
    - xcode
    - macOS
  <<: *script
  variables:
    <<: *macOS_vars 
    PREFIX: Rx

Reactive macOS - OS 10.12:
  stage: reactive
  cache:
    <<: *cache_paths
    key: macOS
  tags:
    - xcode
    - macOS
  <<: *script
  variables:
    <<: *macOS_vars
    PREFIX: Reactive

# tvOS
Apple TV 1080p - OS 10.2:
  stage: moya
  cache:
    <<: *cache_paths
    key: tvOS
  tags:
    - xcode
    - tvOS
  <<: *script
  variables:
    <<: *tvOS_vars

Rx Apple TV 1080p - OS 10.2:
  stage: reactive
  cache:
    <<: *cache_paths
    key: tvOS
  tags:
    - xcode
    - tvOS
  <<: *script
  variables:
    <<: *tvOS_vars
    PREFIX: Rx

Reactive Apple TV 1080p - OS 10.2:
  stage: reactive
  cache:
    <<: *cache_paths
    key: tvOS
  tags:
    - xcode
    - tvOS
  <<: *script
  variables:
    <<: *tvOS_vars
    PREFIX: Reactive

# watchOS
Apple Watch Series 2 - OS 3.1:
  stage: moya
  cache:
    <<: *cache_paths
    key: watchOS
  tags:
    - xcode
    - watchOS
  <<: *script
  variables:
    <<: *watchOS_vars

Rx Apple Watch Series 2 - OS 3.1:
  stage: reactive
  cache:
    <<: *cache_paths
    key: watchOS
  tags:
    - xcode
    - watchOS
  <<: *script
  variables:
    <<: *watchOS_vars
    PREFIX: Rx

Reactive Apple Watch Series 2 - OS 3.1:
  stage: reactive
  cache:
    <<: *cache_paths
    key: watchOS
  tags:
    - xcode
    - watchOS
  <<: *script
  variables:
    <<: *watchOS_vars
    PREFIX: Reactive

############################################
# JOBS - STAGE: Demo

demo:
  stage: demo
  when: on_success
  tags:
    - xcode
    - iOS
  variables:
    <<: *iOS_vars
  before_script:
    - echo "Demo"
  script:
    - cd Demo
    - pod install
    - xcodebuild -workspace "Demo.xcworkspace" -scheme "Demo" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;

############################################
# JOBS - STAGE: PODLINT

podlint:
  stage: podlint
  when: on_success
  tags:
    - xcode
  before_script:
    - echo "Podlint"
  script:
    - pod lib lint --allow-warnings