language: objective-c
osx_image: xcode8.2

cache:
  directories:
  - Carthage

env:
  global:
    - FRAMEWORK_NAME=MoyaModelMapper
    - XCODE_PROJECT=MoyaModelMapper.xcodeproj
    - IOS_FRAMEWORK_SCHEME="MoyaModelMapper-iOS"
    - MACOS_FRAMEWORK_SCHEME="MoyaModelMapper-macOS"
    - TVOS_FRAMEWORK_SCHEME="MoyaModelMapper-tvOS"
    - WATCHOS_FRAMEWORK_SCHEME="MoyaModelMapper-watchOS"
    - IOS_SDK=iphonesimulator10.2
    - MACOS_SDK=macosx10.12
    - TVOS_SDK=appletvsimulator10.1
    - WATCHOS_SDK=watchsimulator3.1
  matrix:
    # MoyaModelMapper
    - CACHE_NAME=JOB1    PREFIX= ""   DESTINATION="platform=watchOS Simulator,OS=3.1,name=Apple Watch - 42mm"          SCHEME="$WATCHOS_FRAMEWORK_SCHEME"   SDK="$WATCHOS_SDK"   RUN_TESTS="NO"    POD_LINT="NO"
    - CACHE_NAME=JOB2    PREFIX= ""   DESTINATION="platform=watchOS Simulator,OS=3.1,name=Apple Watch Series 2 - 42mm" SCHEME="$WATCHOS_FRAMEWORK_SCHEME"   SDK="$WATCHOS_SDK"   RUN_TESTS="NO"    POD_LINT="NO"

    - CACHE_NAME=JOB3    PREFIX= ""   DESTINATION="platform=iOS Simulator,OS=10.1,name=iPhone 7"   SCHEME="$IOS_FRAMEWORK_SCHEME"       SDK="$IOS_SDK"       RUN_TESTS="YES"   POD_LINT="YES"
    - CACHE_NAME=JOB4    PREFIX= ""   DESTINATION="platform=iOS Simulator,OS=9.3,name=iPhone 6"    SCHEME="$IOS_FRAMEWORK_SCHEME"       SDK="$IOS_SDK"       RUN_TESTS="YES"   POD_LINT="NO"

    - CACHE_NAME=JOB5    PREFIX= ""   DESTINATION="OS=10.0,name=Apple TV 1080p"                    SCHEME="$TVOS_FRAMEWORK_SCHEME"      SDK="$TVOS_SDK"      RUN_TESTS="YES"   POD_LINT="NO"
    - CACHE_NAME=JOB6    PREFIX= ""   DESTINATION="OS=9.0,name=Apple TV 1080p"                     SCHEME="$TVOS_FRAMEWORK_SCHEME"      SDK="$TVOS_SDK"      RUN_TESTS="YES"   POD_LINT="NO"

    - CACHE_NAME=JOB7    PREFIX= ""   DESTINATION="platform=OS X,arch=x86_64"                      SCHEME="$MACOS_FRAMEWORK_SCHEME"     SDK="$MACOS_SDK"     RUN_TESTS="YES"   POD_LINT="NO"

    # RxMoyaModelMapper
    - CACHE_NAME=JOB8    PREFIX= "Rx"   DESTINATION="platform=watchOS Simulator,OS=3.1,name=Apple Watch - 42mm"                 SCHEME="$WATCHOS_FRAMEWORK_SCHEME"   SDK="$WATCHOS_SDK"   RUN_TESTS="NO"    POD_LINT="NO"
    - CACHE_NAME=JOB9    PREFIX= "Rx"   DESTINATION="platform=watchOS Simulator,OS=3.1,name=Apple Watch Series 2 - 42mm"              SCHEME="$WATCHOS_FRAMEWORK_SCHEME"   SDK="$WATCHOS_SDK"   RUN_TESTS="NO"    POD_LINT="NO"

    - CACHE_NAME=JOB10   PREFIX= "Rx"   DESTINATION="platform=iOS Simulator,OS=10.1,name=iPhone 7"   SCHEME="$IOS_FRAMEWORK_SCHEME"       SDK="$IOS_SDK"       RUN_TESTS="YES"   POD_LINT="YES"
    - CACHE_NAME=JOB11   PREFIX= "Rx"   DESTINATION="platform=iOS Simulator,OS=9.3,name=iPhone 6"    SCHEME="$IOS_FRAMEWORK_SCHEME"       SDK="$IOS_SDK"       RUN_TESTS="YES"   POD_LINT="NO"

    - CACHE_NAME=JOB12   PREFIX= "Rx"   DESTINATION="OS=10.0,name=Apple TV 1080p"                    SCHEME="$TVOS_FRAMEWORK_SCHEME"      SDK="$TVOS_SDK"      RUN_TESTS="YES"   POD_LINT="NO"
    - CACHE_NAME=JOB13   PREFIX= "Rx"   DESTINATION="OS=9.0,name=Apple TV 1080p"                     SCHEME="$TVOS_FRAMEWORK_SCHEME"      SDK="$TVOS_SDK"      RUN_TESTS="YES"   POD_LINT="NO"

    - CACHE_NAME=JOB14   PREFIX= "Rx"   DESTINATION="platform=OS X,arch=x86_64"                      SCHEME="$MACOS_FRAMEWORK_SCHEME"     SDK="$MACOS_SDK"     RUN_TESTS="YES"   POD_LINT="NO"

before_install:
  - brew update
  # Cocoapod
  - brew install cocoapods || brew upgrade cocoapods
  # SwiftLint
  - brew install swiftlint || brew upgrade swiftlint
  # Carthage tools
  - brew install carthage || brew upgrade carthage
  - curl -L -O https://github.com/YPlan/CartfileDiff/releases/download/0.1/CartfileDiff.pkg
  - sudo installer -pkg CartfileDiff.pkg -target /
  # xcpretty
  - gem install xcpretty
  # danger
  - gem install danger danger-swiftlint

before_script:
  # bootstrap the dependencies for the project
  # you can remove if you don't have dependencies
  - if [[ $SCHEME == $IOS_FRAMEWORK_SCHEME ]];then
      export PLATFORM=iOS;
    elif [[ $SCHEME == $MACOS_FRAMEWORK_SCHEME ]];then
      export PLATFORM=macOS;
    elif [[ $SCHEME == $TVOS_FRAMEWORK_SCHEME ]];then
      export PLATFORM=tvOS;
    else
        export PLATFORM=watchOS;
    fi
  - PLATFORM=$PLATFORM ./scripts/bootstrap-if-needed

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug and Run Tests if specified
  - echo "BUILD FOR DEBUG"
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -project "$XCODE_PROJECT" -scheme "$PREFIX$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
    else
      xcodebuild -project "$XCODE_PROJECT" -scheme "$PREFIX$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

  # Build Framework in Release and Run Tests if specified
  - echo "BUILD FOR RELEASE"
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -project "$XCODE_PROJECT" -scheme "$PREFIX$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
    else
      xcodebuild -project "$XCODE_PROJECT" -scheme "$PREFIX$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

  # Build Example in Debug if specified
  - if [ $SDK == $IOS_SDK ]; then
      cd Demo
      pod install
      xcodebuild -project "Demo.xcworkspace" -scheme "Demo" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

  # Run `pod lib lint` if specified
  #- if [ $POD_LINT == "YES" ]; then
  #    pod lib lint --allow-warnings --verbose
  #  fi

after_success:
  - danger
  - bash <(curl -s https://codecov.io/bash)

#before_deploy:
#  - carthage build --no-skip-current
#  - carthage archive $FRAMEWORK_NAME
