language: objective-c
os: osx
osx_image: xcode8.3

rvm: 2.2.0

cache:
  cocoapods: true
  directories:
  - Carthage

xcode_project: MoyaModelMapper.xcodeproj 

xcode_scheme:
  - MoyaModelMapper
  - RxMoyaModelMapper
  - ReactiveMoyaModelMapper

env:
  - CACHE_NAME=iOS        PLATFORM=iOS        ACTION=test    POD_LINT="YES"
  - CACHE_NAME=macOS      PLATFORM=macOS      ACTION=test
  - CACHE_NAME=tvOS       PLATFORM=tvOS       ACTION=test
  - CACHE_NAME=watchOS    PLATFORM=watchOS    ACTION=build

before_install:
  - brew update
  # Cocoapod
  - brew install cocoapods
  # SwiftLint
  - brew outdated swiftlint || brew upgrade swiftlint
  # Carthage tools
  - brew outdated carthage || brew upgrade carthage
  - curl -L -O https://github.com/YPlan/CartfileDiff/releases/download/0.1/CartfileDiff.pkg
  - sudo installer -pkg CartfileDiff.pkg -target /
  # xcpretty
  - gem install xcpretty
  # danger
  - gem install danger danger-swiftlint

before_script:
  - export POD_LINT="NO"

  - case "$PLATFORM" in
      "iOS")
        export SDK="iphonesimulator10.3";
        export DESTINATION="platform=iOS Simulator,OS=10.3,name=iPhone 7";
        ;;
      "macOS")
        export SDK="macosx10.12";
        export DESTINATION="platform=OS X,arch=x86_64";
        ;;
      "tvOS")
        export SDK="appletvsimulator10.2";
        export DESTINATION="OS=10.2,name=Apple TV 1080p";
        ;;
      "watchOS")
        export SDK="watchsimulator3.2";
        export DESTINATION="platform=watchOS Simulator,OS=3.2,name=Apple Watch Series 2 - 42mm";
        ;;
    esac

  # bootstrap the dependencies for the project
  # you can remove if you don't have dependencies
  - PLATFORM=$PLATFORM ./scripts/bootstrap-if-needed

script:
  - set -o pipefail
  
  # Build Framework in Debug and Run Tests if specified
  - xcodebuild clean -project "$TRAVIS_XCODE_PROJECT" -scheme "$TRAVIS_XCODE_SCHEME" | xcpretty
  - xcodebuild -project "$TRAVIS_XCODE_PROJECT" -scheme "$TRAVIS_XCODE_SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES $ACTION | xcpretty;

  # Build Framework in Release and Run Tests if specified
  - xcodebuild clean -project "$TRAVIS_XCODE_PROJECT" -scheme "$TRAVIS_XCODE_SCHEME" | xcpretty
  - xcodebuild -project "$TRAVIS_XCODE_PROJECT" -scheme "$TRAVIS_XCODE_SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES $ACTION | xcpretty;

  # Build Example in Debug if specified
  - if [ $PLATFORM == "iOS" ] && [ $TRAVIS_XCODE_SCHEME == "MoyaModelMapper" ]; then
      cd Demo;
      pod install;
      xcodebuild -workspace "Demo.xcworkspace" -scheme "Demo" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
      cd ..;
    fi

  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ] && [ $TRAVIS_XCODE_SCHEME == "MoyaModelMapper" ] && [ $TRAVIS_PULL_REQUEST != "false" ]; then
      pod repo update > /dev/null;
      travis_wait 60 pod lib lint --allow-warnings;
    fi

after_success:
  - danger
  - bash <(curl -s https://codecov.io/bash)

#before_deploy:
#  - carthage build --no-skip-current
#  - carthage archive $FRAMEWORK_NAME
